export const DAY_TEMPERATURE = 'DAY TEMPERATURE'
export const NIGHT_TEMPERATURE = 'NIGHT_TEMPERATURE TEMPERATURE'
export const MORNING_TEMPERATURE = 'MORNING_TEMPERATURE TEMPERATURE'
export const HUMIDITY = 'DAY HUMIDITY'